Collections:
  - Name: PPYOLOE
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - Synchronize BN
      Training Resources: 8x A100 GPUs
      Architecture:
        - PPYOLOECSPResNet
        - PPYOLOECSPPAFPN
    Paper:
      URL: https://arxiv.org/abs/2203.16250
      Title: 'PP-YOLOE: An evolved version of YOLO'
    README: configs/ppyoloe/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.0.1/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.0.1

Models:
  - Name: ppyoloe_plus_s_fast_8xb8-80e_coco
    In Collection: PPYOLOE
    Config: configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
    Metadata:
      Training Memory (GB): 4.7
      Epochs: 80
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 43.5
    Weights: https://download.openmmlab.com/mmyolo/v0/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco/ppyoloe_plus_s_fast_8xb8-80e_coco_20230101_154052-9fee7619.pth
  - Name: ppyoloe_plus_m_fast_8xb8-80e_coco
    In Collection: PPYOLOE
    Config: configs/ppyoloe/ppyoloe_plus_m_fast_8xb8-80e_coco.py
    Metadata:
      Training Memory (GB): 8.4
      Epochs: 80
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 49.5
    Weights: https://download.openmmlab.com/mmyolo/v0/ppyoloe/ppyoloe_plus_m_fast_8xb8-80e_coco/ppyoloe_plus_m_fast_8xb8-80e_coco_20230104_193132-e4325ada.pth
  - Name: ppyoloe_plus_L_fast_8xb8-80e_coco
    In Collection: PPYOLOE
    Config: configs/ppyoloe/ppyoloe_plus_L_fast_8xb8-80e_coco.py
    Metadata:
      Training Memory (GB): 13.2
      Epochs: 80
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 52.6
    Weights: https://download.openmmlab.com/mmyolo/v0/ppyoloe/ppyoloe_plus_l_fast_8xb8-80e_coco/ppyoloe_plus_l_fast_8xb8-80e_coco_20230102_203825-1864e7b3.pth
  - Name: ppyoloe_plus_x_fast_8xb8-80e_coco
    In Collection: PPYOLOE
    Config: configs/ppyoloe/ppyoloe_plus_x_fast_8xb8-80e_coco.py
    Metadata:
      Training Memory (GB): 19.1
      Epochs: 80
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 54.2
    Weights: https://download.openmmlab.com/mmyolo/v0/ppyoloe/ppyoloe_plus_x_fast_8xb8-80e_coco/ppyoloe_plus_x_fast_8xb8-80e_coco_20230104_194921-8c953949.pth
