Collections:
  - Name: YOLOv5
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - AMP
      Training Resources: 1x A100 GPU
      Architecture:
        - CSPDarkNet
        - PAFPN
    README: configs/yolov5/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.1.0/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.1.0

Models:
  - Name: yolov5_n-v61_fast_1xb64-50e_voc
    In Collection: YOLOv5
    Config: configs/yolov5/voc/yolov5_n-v61_fast_1xb64-50e_voc.py
    Metadata:
      Training Memory (GB): 3.5
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.2
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_fast_1xb64-50e_voc/yolov5_n-v61_fast_1xb64-50e_voc_20221017_234254-f1493430.pth
  - Name: yolov5_s-v61_fast_1xb64-50e_voc
    In Collection: YOLOv5
    Config: configs/yolov5/voc/yolov5_s-v61_fast_1xb64-50e_voc.py
    Metadata:
      Training Memory (GB): 6.5
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 62.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_fast_1xb64-50e_voc/yolov5_s-v61_fast_1xb64-50e_voc_20221017_234156-0009b33e.pth
  - Name: yolov5_m-v61_fast_1xb64-50e_voc
    In Collection: YOLOv5
    Config: configs/yolov5/voc/yolov5_m-v61_fast_1xb64-50e_voc.py
    Metadata:
      Training Memory (GB): 12.0
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 70.1
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_m-v61_fast_1xb64-50e_voc/yolov5_m-v61_fast_1xb64-50e_voc_20221017_114138-815c143a.pth
  - Name: yolov5_l-v61_fast_1xb32-50e_voc
    In Collection: YOLOv5
    Config: configs/yolov5/voc/yolov5_l-v61_fast_1xb32-50e_voc.py
    Metadata:
      Training Memory (GB): 10.0
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 72.9
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_l-v61_fast_1xb32-50e_voc/yolov5_l-v61_fast_1xb32-50e_voc_20221017_045500-edc7e0d8.pth
