Collections:
  - Name: YOLOv5
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - AMP
        - Synchronize BN
      Training Resources: 8x A100 GPUs
      Architecture:
        - CSPDarkNet
        - PAFPN
    README: configs/yolov5/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.1.0/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.1.0
  - Name: YOLOv5_VOC
    Metadata:
      Training Data: VOC
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - AMP
      Training Resources: 1x A100 GPU
      Architecture:
        - CSPDarkNet
        - PAFPN
    README: configs/yolov5/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.1.0/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.1.0

Models:
  - Name: yolov5_n-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 1.5
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 28.0
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco/yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739-b804c1ad.pth
  - Name: yolov5_s-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 2.7
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth
  - Name: yolov5_m-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_m-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 5.0
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 45.3
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_m-v61_syncbn_fast_8xb16-300e_coco/yolov5_m-v61_syncbn_fast_8xb16-300e_coco_20220917_204944-516a710f.pth
  - Name: yolov5_l-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_l-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 8.1
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 48.8
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_l-v61_syncbn_fast_8xb16-300e_coco/yolov5_l-v61_syncbn_fast_8xb16-300e_coco_20220917_031007-096ef0eb.pth
  - Name: yolov5_n-p6-v62_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_n-p6-v62_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 5.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 35.9
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-p6-v62_syncbn_fast_8xb16-300e_coco/yolov5_n-p6-v62_syncbn_fast_8xb16-300e_coco_20221027_224705-d493c5f3.pth
  - Name: yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 10.5
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.4
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco_20221027_215044-58865c19.pth
  - Name: yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 19.1
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.3
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco_20221027_230453-49564d58.pth
  - Name: yolov5_l-p6-v62_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_l-p6-v62_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 30.5
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 53.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_l-p6-v62_syncbn_fast_8xb16-300e_coco/yolov5_l-p6-v62_syncbn_fast_8xb16-300e_coco_20221027_234308-7a2ba6bf.pth
  - Name: yolov5_n-v61_fast_1xb64-50e_voc
    In Collection: YOLOv5_VOC
    Config: configs/yolov5/voc/yolov5_n-v61_fast_1xb64-50e_voc.py
    Metadata:
      Training Memory (GB): 3.5
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.2
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_fast_1xb64-50e_voc/yolov5_n-v61_fast_1xb64-50e_voc_20221017_234254-f1493430.pth
  - Name: yolov5_s-v61_fast_1xb64-50e_voc
    In Collection: YOLOv5_VOC
    Config: configs/yolov5/voc/yolov5_s-v61_fast_1xb64-50e_voc.py
    Metadata:
      Training Memory (GB): 6.5
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 62.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_fast_1xb64-50e_voc/yolov5_s-v61_fast_1xb64-50e_voc_20221017_234156-0009b33e.pth
  - Name: yolov5_m-v61_fast_1xb64-50e_voc
    In Collection: YOLOv5_VOC
    Config: configs/yolov5/voc/yolov5_m-v61_fast_1xb64-50e_voc.py
    Metadata:
      Training Memory (GB): 12.0
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 70.1
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_m-v61_fast_1xb64-50e_voc/yolov5_m-v61_fast_1xb64-50e_voc_20221017_114138-815c143a.pth
  - Name: yolov5_l-v61_fast_1xb32-50e_voc
    In Collection: YOLOv5_VOC
    Config: configs/yolov5/voc/yolov5_l-v61_fast_1xb32-50e_voc.py
    Metadata:
      Training Memory (GB): 10.0
      Epochs: 50
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 73.1
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_l-v61_fast_1xb32-50e_voc/yolov5_l-v61_fast_1xb32-50e_voc_20221017_045500-edc7e0d8.pth
