Collections:
  - Name: YOLOv5
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Nesterov
        - Weight Decay
        - AMP
        - Synchronize BN
      Training Resources: 8x A100 GPUs
      Architecture:
        - CSPDarkNet
        - PAFPN
    README: configs/yolov5/README.md
    Code:
      URL: https://github.com/open-mmlab/mmyolo/blob/v0.1.0/mmyolo/models/detectors/yolo_detector.py#L12
      Version: v0.1.0

Models:
  - Name: yolov5_n-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 1.5
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 28.0
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_n-v61_syncbn_fast_8xb16-300e_coco/yolov5_n-v61_syncbn_fast_8xb16-300e_coco_20220919_090739-b804c1ad.pth
  - Name: yolov5_s-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 2.7
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.7
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth
  - Name: yolov5_m-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_m-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 5.0
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 45.3
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_m-v61_syncbn_fast_8xb16-300e_coco/yolov5_m-v61_syncbn_fast_8xb16-300e_coco_20220917_204944-516a710f.pth
  - Name: yolov5_l-v61_syncbn_fast_8xb16-300e_coco
    In Collection: YOLOv5
    Config: configs/yolov5/yolov5_l-v61_syncbn_fast_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 8.1
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 48.8
    Weights: https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_l-v61_syncbn_fast_8xb16-300e_coco/yolov5_l-v61_syncbn_fast_8xb16-300e_coco_20220917_031007-096ef0eb.pth
